### PR TITLE
v1.1.3

### PR DESCRIPTION
**Pull request by bendog**
Release 1.1.2 to NPM
@lilfolr do i need to bump this first with npm ?

### CODE REVIEW

**Comment by lilfolr** [comment]
Yeah, change the version in `package.json`
You can push that straight to master

**Comment by bendog** [comment]
@lilfolr ready to go?

**Review by lilfolr — APPROVED** [review]

**Comment by bendog** [comment]
@lilfolr any idea why travis is failing?

**Comment by lilfolr** [comment]
A quick google returns this - https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154
Probably the issue

**Comment by bendog** [comment]
image

**Pull request merged**
