### PR TITLE
v1.1.0 update to select logic 

### PR DESCRIPTION
**Pull request by bendog**
## Proposed Change:
UI now matches what the select logic does
Entire row is highlighted from start time to finish time.

## Change type

- [ ] Bugfix
- [X] New feature

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by bendog** [comment]
> Would be cool to keep on top of the unit tests :)

I agree, but I wasn't sure how to test for this as it's purely UI driven?

**Comment by vasdee** [comment]
Not doubting your mad skills here, but I would have thought this be one of the more time consuming issues to solve? Look forward to seeing it in action!

Leighton is a bit of a fan of rebasing too, this might be a good candidate here before merging

**Comment by lilfolr** [comment]
True, that is more tricky.
You could test `getNearestRowObject` - maybe mock up a fake div object.

And yeah, maybe some squashing :)

**Comment by bendog** [comment]
I can do a squash merge

**Comment by bendog** [comment]
> Can you check this work for multi-row selection, when starting from a lower row and dragging up?

damn it doesn't work

**Comment by bendog** [comment]
works now

**Comment by bendog** [comment]
@lilfolr which browser? 
I can't replicate it on mine

**Comment by lilfolr** [comment]
https://drive.google.com/file/d/1reHrE1EeY9zr4wVDQYDmBzCAKXFTpdHZ/view?usp=sharing

**Comment by bendog** [comment]
I had to scroll down a bit first to trigger it.
ok this is tricky... I'll have to figure out how to clip the selection box from going outside the timeline

**Comment by bendog** [comment]
@lilfolr are you interested in the fix?

**Comment by lilfolr** [comment]
I'll trust it works 😊
Feel free to merge

**Comment by bendog** [comment]
> I'll trust it works 😊
> Feel free to merge

I don't trust myself anymore after missing those bugs, i hate frontend work, too many edge cases.

**Pull request merged**
