### PR TITLE
Allow timeline custom resolution

### PR DESCRIPTION
**Pull request by uncledent**
## Proposed Change:
Pass resolution props to timeline

## Change type
- [x] Bugfix
- [] New feature

## Checklist

- [] I have added tests that prove my fix is effective or that my feature works
- [] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by vasdee** [comment]
will this impact the demo @lilfolr ?

**Comment by lilfolr** [comment]
Shouldn't, but I'll check tonight

**Comment by lilfolr** [comment]
Demo looks fine. Happy to merge if you are

**Comment by bendog** [comment]
@lilfolr not sure why travis isn't reporting the status back to GitHub, it seems to have run according to travis

**Comment by lilfolr** [comment]
Yeah I've seen travis 'forget' to report the result before.
I'll merge this, and you can release to `release/npm` if you're comfortable with the change @bendog

**Comment by bendog** [comment]
@lilfolr please do

**Pull request merged**
